name: handycraft
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0
  page_transition: ^2.0.2
  syncfusion_flutter_sliders: ^19.1.64-beta
  flutter_signin_button: ^2.0.0
  google_fonts:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  get: ^4.6.5
  another_flushbar: ^1.12.29
  dio: ^4.0.3
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.9.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this
  assets:
    - assets/images/
    - assets/icons/image.jpg
    - assets/icons/mapImage.png
    - assets/icons/blackMap.png
    - assets/icons/navigate.png
    - assets/icons/icon.png
    - assets/icons/tel.png
    - assets/icons/ProfileImage.png
    - assets/icons/Profile.png
    - assets/icons/Review.png
    - assets/icons/Payment.png
    - assets/icons/notification.png
    - assets/icons/Settings.png
    - assets/icons/Privacy.png
    - assets/icons/cross.png
    - assets/icons/tick.png
    - assets/icons/onboarding_1.png
    - assets/icons/onboarding_2.png
    - assets/icons/onboarding_3.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PoppinsBlack
      fonts:
        - asset: assets/Poppins/Poppins-Black.ttf
    - family: PoppinsBlackItalic
      fonts:
        - asset: assets/Poppins/Poppins-BlackItalic.ttf

    - family: PoppinsBold
      fonts:
        - asset: assets/Poppins/Poppins-Bold.ttf
    - family: PoppinsBoldItalic
      fonts:
        - asset: assets/Poppins/Poppins-BoldItalic.ttf

    - family: PoppinsExtraBold
      fonts:
        - asset: assets/Poppins/Poppins-ExtraBold.ttf
    - family: PoppinsExtraBoldItalic
      fonts:
        - asset: assets/Poppins/Poppins-ExtraBoldItalic.ttf

    - family: PoppinsExtraLight
      fonts:
        - asset: assets/Poppins/Poppins-ExtraLight.ttf
    - family: PoppinsExtraLightItalic
      fonts:
        - asset: assets/Poppins/Poppins-ExtraLightItalic.ttf
    - family: PoppinsItalic
      fonts:
        - asset: assets/Poppins/Poppins-Italic.ttf
    - family: PoppinsLight
      fonts:
        - asset: assets/Poppins/Poppins-Light.ttf

    - family: PoppinsLightItalic
      fonts:
        - asset: assets/Poppins/Poppins-LightItalic.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/Poppins/Poppins-Medium.ttf
    - family: PoppinsMediumItalic
      fonts:
        - asset: assets/Poppins/Poppins-MediumItalic.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/Poppins/Poppins-Regular.ttf

    - family: PoppinsSemiBold
      fonts:
        - asset: assets/Poppins/Poppins-SemiBold.ttf
    - family: PoppinsSemiBoldItalic
      fonts:
        - asset: assets/Poppins/Poppins-SemiBoldItalic.ttf
    - family: PoppinsThin
      fonts:
        - asset: assets/Poppins/Poppins-Thin.ttf
    - family: PoppinsThinItalic
      fonts:
        - asset: assets/Poppins/Poppins-ThinItalic.ttf
